// src/utils/translate-note.ts
// Dictionnaire de traduction EN → FR pour les notes de parfum et accords.
// ⚠️  Traduit à l'affichage uniquement — NE PAS utiliser au stockage.
// Le fallback retourne la note originale si non trouvée.

// ─── NOTES (ingrédients olfactifs) ──────────────────────────

const NOTE_DICT: Record<string, string> = {
  // Agrumes
  "bergamot": "bergamote",
  "sicilian bergamot": "bergamote de Sicile",
  "calabrian bergamot": "bergamote de Calabre",
  "lemon": "citron",
  "italian lemon": "citron d'Italie",
  "sicilian lemon": "citron de Sicile",
  "californian lemon": "citron de Californie",
  "amalfi lemon": "citron d'Amalfi",
  "grapefruit": "pamplemousse",
  "mandarin orange": "mandarine",
  "mandarin": "mandarine",
  "italian mandarin": "mandarine d'Italie",
  "green mandarin": "mandarine verte",
  "orange": "orange",
  "bitter orange": "orange amère",
  "blood orange": "orange sanguine",
  "sicilian orange": "orange de Sicile",
  "tangerine": "tangerine",
  "lime": "citron vert",
  "citruses": "agrumes",
  "citrus": "agrumes",
  "sicilian citruses": "agrumes de Sicile",
  "yuzu": "yuzu",
  "petitgrain": "petitgrain",

  // Fruits
  "apple": "pomme",
  "green apple": "pomme verte",
  "pear": "poire",
  "peach": "pêche",
  "white peach": "pêche blanche",
  "apricot": "abricot",
  "blackberry": "mûre",
  "black currant": "cassis",
  "cassis": "cassis",
  "raspberry": "framboise",
  "strawberry": "fraise",
  "pineapple": "ananas",
  "plum": "prune",
  "damask plum": "prune de Damas",
  "litchi": "litchi",
  "cherry": "cerise",
  "coconut": "noix de coco",
  "mango": "mangue",
  "passionfruit": "fruit de la passion",
  "nectarine": "nectarine",
  "cranberry": "canneberge",
  "melon": "melon",
  "boysenberry": "mûre de Boysen",
  "red berries": "fruits rouges",
  "wild berries": "baies sauvages",
  "berry fruits": "fruits rouges",
  "grapes": "raisin",
  "watermelon": "pastèque",
  "fig": "figue",
  "rhubarb leaf": "feuille de rhubarbe",

  // Épicés
  "pink pepper": "poivre rose",
  "black pepper": "poivre noir",
  "black and pink pepper": "poivre noir et rose",
  "pepper": "poivre",
  "sichuan pepper": "poivre du Sichuan",
  "green pepper": "poivre vert",
  "saffron": "safran",
  "cardamom": "cardamome",
  "cardamon": "cardamome",
  "guatemalan cardamom": "cardamome du Guatemala",
  "cinnamon": "cannelle",
  "clove": "clou de girofle",
  "cloves": "clou de girofle",
  "nutmeg": "noix de muscade",
  "ginger": "gingembre",
  "caraway": "carvi",
  "coriander": "coriandre",
  "cumin": "cumin",
  "anise": "anis",
  "licorice": "réglisse",
  "curry tree": "kaloupilé",
  "basil": "basilic",
  "thyme": "thym",
  "red thyme": "thym rouge",
  "sage": "sauge",
  "clary sage": "sauge sclarée",
  "rosemary": "romarin",
  "tarragon": "estragon",
  "oregano": "origan",
  "exotic spices": "épices exotiques",
  "bay leaf": "feuille de laurier",

  // Floraux
  "rose": "rose",
  "bulgarian rose": "rose de Bulgarie",
  "turkish rose": "rose de Turquie",
  "jasmine": "jasmin",
  "lavender": "lavande",
  "iris": "iris",
  "white iris": "iris blanc",
  "violet": "violette",
  "tuberose": "tubéreuse",
  "gardenia": "gardénia",
  "ylang-ylang": "ylang-ylang",
  "neroli": "néroli",
  "orange blossom": "fleur d'oranger",
  "magnolia": "magnolia",
  "peony": "pivoine",
  "muguet": "muguet",
  "lily of the valley": "muguet",
  "lily": "lys",
  "water lily": "nénuphar",
  "freesia": "freesia",
  "hyacinth": "jacinthe",
  "narcissus": "narcisse",
  "orchid": "orchidée",
  "geranium": "géranium",
  "heliotrope": "héliotrope",
  "mimosa": "mimosa",
  "osmanthus": "osmanthus",
  "chamomile": "camomille",
  "honeysuckle": "chèvrefeuille",
  "floral notes": "notes florales",

  // Boisés
  "cedar": "cèdre",
  "sandalwood": "bois de santal",
  "vetiver": "vétiver",
  "patchouli": "patchouli",
  "oakmoss": "mousse de chêne",
  "guaiac wood": "bois de gaïac",
  "cypress": "cyprès",
  "pine": "pin",
  "fir": "sapin",
  "birch": "bouleau",
  "ebony": "ébène",
  "cashmere wood": "bois de cachemire",
  "amberwood": "bois d'ambre",
  "oud": "oud",
  "agarwood": "bois d'agar",

  // Résines & Baumes
  "amber": "ambre",
  "incense": "encens",
  "frankincense": "oliban",
  "myrrh": "myrrhe",
  "benzoin": "benjoin",
  "labdanum": "labdanum",
  "tolu balsam": "baume de Tolu",
  "balsamic notes": "notes balsamiques",
  "resins": "résines",
  "opoponax": "opoponax",
  "elemi": "élémi",
  "styrax": "styrax",

  // Muscs & Cuir
  "musk": "musc",
  "white musk": "musc blanc",
  "ambrette (musk mallow)": "ambrette",
  "ambrette": "ambrette",
  "castoreum": "castoréum",
  "civet": "civette",
  "civetta": "civette",
  "leather": "cuir",
  "suede": "daïm",

  // Verts & Aquatiques
  "green notes": "notes vertes",
  "water notes": "notes aquatiques",
  "marine notes": "notes marines",
  "sea salt": "sel marin",
  "grass": "herbe coupée",
  "galbanum": "galbanum",
  "artemisia": "armoise",
  "wormwood": "absinthe",
  "ivy": "lierre",
  "moss": "mousse",
  "oak": "chêne",
  "tea": "thé",
  "green tea": "thé vert",
  "mate": "maté",
  "verbena": "verveine",
  "angelica": "angélique",
  "papyrus": "papyrus",

  // Gourmands
  "vanilla": "vanille",
  "vanila": "vanille",
  "bourbon vanilla": "vanille Bourbon",
  "madagascar vanilla": "vanille de Madagascar",
  "vanilla bean": "gousse de vanille",
  "vanilla sugar": "sucre vanillé",
  "tonka bean": "fève tonka",
  "caramel": "caramel",
  "chocolate": "chocolat",
  "cocoa": "cacao",
  "cacao": "cacao",
  "honey": "miel",
  "white honey": "miel blanc",
  "almond": "amande",
  "bitter almond": "amande amère",
  "sweet almond": "amande douce",
  "almond milk": "lait d'amande",
  "praline": "praliné",
  "coffee": "café",
  "roasted coffee beans": "grains de café torréfiés",
  "chestnut": "marron",
  "hazelnut": "noisette",
  "marshmallow": "guimauve",
  "cotton candy": "barbe à papa",
  "sugar": "sucre",
  "brown sugar": "sucre roux",
  "lactonic": "lacté",
  "milk": "lait",
  "ice cream": "glace",
  "popcorn": "pop-corn",
  "carrot": "carotte",

  // Synthétiques
  "ambroxan": "ambroxan",
  "iso e super": "iso e super",
  "hedione": "hédione",
  "cashmeran": "cashmeran",
  "norlimbanol": "norlimbanol",
  "sylkolide": "sylkolide",
  "mahonial": "mahonial",
  "pomarose": "pomarose",
  "belambra tree": "belambra",
  "calone": "calone",

  // Alcooliques & Tabac
  "cannabis": "cannabis",
  "rum": "rhum",
  "whiskey": "whisky",
  "gin": "gin",
  "cognac": "cognac",
  "tobacco": "tabac",
  "smoke": "fumée",

  // Divers
  "powder": "poudré",
  "aldehydes": "aldéhydes",
  "ozonic": "ozoné",
  "mineral": "minéral",
  "earthy notes": "notes terreuses",
  "spices": "épices",
  "woods": "bois",
  "acacia": "acacia",
  "melon or sweet clover": "mélilot",
};

// ─── ACCORDS (familles olfactives) ──────────────────────────

const ACCORD_DICT: Record<string, string> = {
  "citrus": "agrumes",
  "woody": "boisé",
  "floral": "floral",
  "white floral": "floral blanc",
  "yellow floral": "floral jaune",
  "rose": "rosé",
  "aromatic": "aromatique",
  "fresh spicy": "épicé frais",
  "warm spicy": "épicé chaud",
  "soft spicy": "épicé doux",
  "amber": "ambré",
  "musky": "musqué",
  "powdery": "poudré",
  "sweet": "sucré",
  "fruity": "fruité",
  "green": "vert",
  "fresh": "frais",
  "aquatic": "aquatique",
  "balsamic": "balsamique",
  "smoky": "fumé",
  "earthy": "terreux",
  "leather": "cuir",
  "animalic": "animal",
  "camphor": "camphré",
  "cannabis": "cannabis",
  "gourmand": "gourmand",
  "herbal": "herbacé",
  "iris": "iris",
  "lavender": "lavande",
  "patchouli": "patchouli",
  "violet": "violette",
  "soapy": "savonneux",
};

// ─── Dictionnaire fusionné ──────────────────────────────────

const FULL_DICT: Record<string, string> = { ...ACCORD_DICT, ...NOTE_DICT };

// ─── Fonction publique ──────────────────────────────────────

/** Traduit une note ou un accord EN → FR avec capitalisation.
 *  Fallback : retourne la valeur originale capitalisée. */
export function translateNote(note: string): string {
  if (!note) return note;
  const key = note.toLowerCase().trim();
  const translated = FULL_DICT[key] ?? note;
  // Capitaliser la première lettre
  return translated.charAt(0).toUpperCase() + translated.slice(1);
}
