// src/utils/translate-note.ts
// Dictionnaire de traduction EN → FR pour les notes de parfum et accords.
// ⚠️  Traduit à l'affichage uniquement — NE PAS utiliser au stockage.
// Le fallback retourne la note originale si non trouvée.

// ─── NOTES (ingrédients olfactifs) ──────────────────────────

const NOTE_DICT: Record<string, string> = {
  "bergamot": "bergamote",
  "sicilian bergamot": "bergamote de Sicile",
  "calabrian bergamot": "bergamote de Calabre",
  "lemon": "citron",
  "italian lemon": "citron d'Italie",
  "sicilian lemon": "citron de Sicile",
  "californian lemon": "citron de Californie",
  "amalfi lemon": "citron d'Amalfi",
  "grapefruit": "pamplemousse",
  "mandarin orange": "mandarine",
  "mandarin": "mandarine",
  "italian mandarin": "mandarine d'Italie",
  "green mandarin": "mandarine verte",
  "orange": "orange",
  "bitter orange": "orange amère",
  "blood orange": "orange sanguine",
  "sicilian orange": "orange de Sicile",
  "tangerine": "tangerine",
  "lime": "citron vert",
  "citruses": "agrumes",
  "citrus": "agrumes",
  "sicilian citruses": "agrumes de Sicile",
  "yuzu": "yuzu",
  "petitgrain": "petitgrain",
  "argentinian lemon": "citron d'Argentine",
  "bergamot blossom": "fleur de Bergamotier",
  "bergamot leaf": "feuille de Bergamotier",
  "bigarade": "bigarade",
  "blood grapefruit": "pamplemousse sanguin",
  "blood mandarin": "mandarine sanguine",
  "buddha's hand": "main de Bouddha",
  "calabrian mandarin": "mandarine de Calabre",
  "calamansi": "calamansi",
  "california orange": "orange de Californie",
  "chinotto": "chinotto",
  "citron": "citron",
  "citron leaf": "feuille de Citronnier",
  "citrus blossom": "fleur d'Agrume",
  "citrus leaf": "feuille d'Agrume",
  "citrus leaves": "feuilles d'Agrumes",
  "citrus and floral notes": "notes d'Agrumes et Florales",
  "citruses water": "eau d'Agrumes",
  "clementine": "clémentine",
  "finger lime": "citron caviar",
  "florida grapefruit": "pamplemousse de Floride",
  "graperfuit": "pamplemousse",
  "grapefruit blossom": "fleur de Pamplemoussier",
  "green orange": "orange verte",
  "green tangerine": "mandarine verte",
  "iced lemon": "citron givré",
  "lemon balm": "mélisse",
  "lemon blossom": "fleur de Citronnier",
  "lemon leaf": "feuille de Citronnier",
  "lemon leaf oil": "huile de Feuille de Citronnier",
  "lemon peel": "zeste de Citron",
  "lemon tree": "citronnier",
  "lemon verbena": "verveine citronnée",
  "lemon zest": "zeste de Citron",
  "lemonade": "limonade",
  "lemongrass": "citronnelle",
  "lime (linden blossom)": "tilleul (Fleur)",
  "lime (linden) blossom": "fleur de Tilleul",
  "lime blossom": "fleur de Tilleul",
  "lime peel": "zeste de Citron vert",
  "limetta": "limette",
  "limoncello": "limoncello",
  "linden blossom": "fleur de Tilleul",
  "mandarin blossom": "fleur de Mandarinier",
  "mandarin leaf": "feuille de Mandarinier",
  "mandora": "mandora",
  "orange flower water": "eau de Fleur d'Oranger",
  "orange honey": "miel d'Oranger",
  "orange leaf": "feuille d'Oranger",
  "orange oil": "huile d'Orange",
  "orange peel": "zeste d'Orange",
  "palestinian sweet lime": "lime Douce de Palestine",
  "pink grapefruit": "pamplemousse rose",
  "rangpur": "rangpour",
  "red mandarin": "mandarine rouge",
  "sicilian mandarin": "mandarine de Sicile",
  "sweet orange": "orange douce",
  "tangelo": "tangelo",
  "tangerine blossom": "fleur de Mandarinier",
  "white bergamot": "bergamote blanche",
  "white grapefruit": "pamplemousse blanc",
  "wild orange": "orange sauvage",
  "yellow mandarin": "mandarine jaune",
  "brazilian mandarin": "mandarine Brésilienne",
  "brazilian orange": "orange Brésilienne",
  "indian mandarin": "mandarine d'Inde",
  "italian orange": "orange d'Italie",
  "apple": "pomme",
  "green apple": "pomme verte",
  "pear": "poire",
  "peach": "pêche",
  "white peach": "pêche blanche",
  "apricot": "abricot",
  "blackberry": "mûre",
  "black currant": "cassis",
  "cassis": "cassis",
  "raspberry": "framboise",
  "strawberry": "fraise",
  "pineapple": "ananas",
  "plum": "prune",
  "damask plum": "prune de Damas",
  "litchi": "litchi",
  "cherry": "cerise",
  "coconut": "noix de coco",
  "mango": "mangue",
  "passionfruit": "fruit de la passion",
  "nectarine": "nectarine",
  "cranberry": "canneberge",
  "melon": "melon",
  "boysenberry": "mûre de Boysen",
  "red berries": "fruits rouges",
  "wild berries": "baies sauvages",
  "berry fruits": "fruits rouges",
  "grapes": "raisin",
  "watermelon": "pastèque",
  "fig": "figue",
  "rhubarb leaf": "feuille de rhubarbe",
  "acai berry": "baie d'Açaï",
  "acerola": "acérola",
  "american apple": "pomme Américaine",
  "apple blossom": "fleur de Pommier",
  "apple leaf": "feuille de Pommier",
  "apple licor": "liqueur de Pomme",
  "apple pie": "tarte aux Pommes",
  "apple shisha accord": "accord Chicha Pomme",
  "apple tree": "pommier",
  "apple tree blossom": "fleur de Pommier",
  "apple juice": "jus de Pomme",
  "applejack": "applejack",
  "apricot blossom": "fleur d'Abricotier",
  "apricot jam": "confiture d'Abricot",
  "avocado": "avocat",
  "banana": "banane",
  "banana flower": "fleur de Bananier",
  "banana leaf": "feuille de Bananier",
  "banana peel": "peau de Banane",
  "barberry": "épine-vinette",
  "bearberry": "busserole",
  "berries": "baies",
  "big strawberry": "grosse Fraise",
  "black cherry": "cerise Noire",
  "black currant blossom": "fleur de Cassis",
  "black pomegranate": "grenade Noire",
  "black currant leaf": "feuille de Cassis",
  "blackberry blossom": "fleur de Ronce",
  "blackberry leaf": "feuille de Ronce",
  "blackcurrant": "cassis",
  "blackcurrant syrup": "sirop de Cassis",
  "blueberry": "myrtille",
  "blueberry leaf": "feuille de Myrtille",
  "burning cherry": "cerise Ardente",
  "cantaloupe": "cantaloup",
  "carambola": "carambole",
  "carambola (star fruit)": "carambole (Fruit Étoile)",
  "cassowary fruit": "fruit du Casoar",
  "cherry blossom": "fleur de Cerisier",
  "cherry jam": "confiture de Cerise",
  "cherry liqueur": "liqueur de Cerise",
  "cherry milk": "lait de Cerise",
  "cherry syrup": "sirop de Cerise",
  "cherry tree": "cerisier",
  "cherry extract": "extrait de Cerise",
  "chinese apricot": "abricot Chinois",
  "chinese grapefruit": "pamplemousse Chinois",
  "chinese litchi": "litchi de Chine",
  "chinese orange": "orange de Chine",
  "chinese plum": "prune de Chine",
  "cloudberry": "plaquebière",
  "coconut blossom": "fleur de Cocotier",
  "coconut leaf": "feuille de Cocotier",
  "coconut milk": "lait de Coco",
  "coconut nectar": "nectar de Coco",
  "coconut powder": "poudre de Coco",
  "coconut water": "eau de Coco",
  "cucumber": "concombre",
  "currant buds": "bourgeons de Cassis",
  "dark plum wu mei": "prune sombre Wu Mei",
  "dates": "dattes",
  "dewberry": "mûre sauvage",
  "dried apple crisp": "chips de Pomme séchée",
  "dried apricot": "abricot sec",
  "dried fruits": "fruits secs",
  "dried plum": "pruneau",
  "durian": "durian",
  "elderflower": "fleur de Sureau",
  "exotic fruits": "fruits exotiques",
  "fig blossom": "fleur de Figuier",
  "fig leaf": "feuille de Figuier",
  "fig milk": "lait de Figue",
  "fig nectar": "nectar de Figue",
  "fig tree": "figuier",
  "fig wood bark": "écorce de Bois de Figuier",
  "forest fruits": "fruits des bois",
  "frosted apple": "pomme givrée",
  "frosted berries": "baies givrées",
  "frosted mango": "mangue givrée",
  "frosted melon": "melon givré",
  "frosted orange": "orange givrée",
  "fruit tea": "thé aux Fruits",
  "fruits": "fruits",
  "gariguette strawberry": "fraise Gariguette",
  "goji berries": "baies de Goji",
  "gooseberry": "groseille à maquereau",
  "granny smith apple": "pomme Granny Smith",
  "grape leaves": "feuilles de Vigne",
  "green anjou pears": "poire d'Anjou verte",
  "green grape": "raisin vert",
  "green mango": "mangue verte",
  "green pear": "poire verte",
  "green plum": "prune verte",
  "greengage": "reine-claude",
  "ground cherry": "physalis",
  "guava": "goyave",
  "guava blossom": "fleur de Goyavier",
  "hog plum": "mombin",
  "honeydew blossom": "fleur de Melon miel",
  "honeydew melon": "melon miel",
  "jackfruit": "fruit du Jacquier",
  "jabuticaba": "jabuticaba",
  "japanese cherry blossom": "fleur de Cerisier du Japon",
  "japanese loquat": "nèfle du Japon",
  "japanese plum": "prune du Japon",
  "juicy apricot": "abricot juteux",
  "kiwi": "kiwi",
  "kumquat": "kumquat",
  "loganberry": "mûre de Logan",
  "longan berries": "baies de Longane",
  "lychee": "litchi",
  "mango blossom": "fleur de Manguier",
  "mangosteen": "mangoustan",
  "maraschino cherry": "cerise au Marasquin",
  "marian plum": "prune de Marian",
  "mirabella plum": "prune mirabelle",
  "mirabelle": "mirabelle",
  "mirabelle plum": "prune mirabelle",
  "nashi pear": "poire nashi",
  "nectarine blossom": "fleur de Nectarinier",
  "papaya": "papaye",
  "papaya flower": "fleur de Papayer",
  "passion fruit": "fruit de la passion",
  "peach blossom": "fleur de Pêcher",
  "peach cream": "crème de Pêche",
  "pear blossom": "fleur de Poirier",
  "pear ice cream": "glace à la Poire",
  "pear leaf": "feuille de Poirier",
  "pear wood": "bois de Poirier",
  "persimmon": "kaki",
  "pineapple leaf": "feuille d'Ananas",
  "pineapple blossom": "fleur d'Ananas",
  "pink litchi": "litchi rose",
  "pitahaya": "pitaya",
  "pitanga": "pitanga",
  "plum blossom": "fleur de Prunier",
  "plum liquor": "liqueur de Prune",
  "plum tree": "prunier",
  "plum wood": "bois de Prunier",
  "pomegranate": "grenade",
  "pomegranate blossom": "fleur de Grenadier",
  "pomegranate seed": "graine de Grenade",
  "pomelo": "pomélo",
  "quandong desert peach": "pêche du Désert quandong",
  "quince": "coing",
  "raisin": "raisin sec",
  "raspberry bloom": "fleur de Framboisier",
  "raspberry blossom": "fleur de Framboisier",
  "raspberry leaf": "feuille de Framboisier",
  "red apple": "pomme rouge",
  "red currant": "groseille rouge",
  "red fruits": "fruits rouges",
  "red fruits smoothie": "smoothie aux Fruits rouges",
  "red litchi": "litchi rouge",
  "red mulberry": "mûre rouge",
  "red peach": "pêche rouge",
  "red currant leaf": "feuille de Groseillier",
  "salak": "salak",
  "sapodilla": "sapotille",
  "seriguela": "seriguela",
  "sour cherry": "griotte",
  "sour cherry blossom": "fleur de Griottier",
  "soursop": "corossol",
  "star apple": "pomme étoilée",
  "star fruit": "carambole",
  "strawberry fizz candy": "bonbon Pétillant à la Fraise",
  "strawberry jam": "confiture de Fraise",
  "strawberry leaf": "feuille de Fraisier",
  "strawberry syrup": "sirop de Fraise",
  "strawberry s'mores": "s'mores à la Fraise",
  "tayberry": "mûre de Tay",
  "toasted coconut": "noix de Coco toastée",
  "tropical fruit": "fruit tropical",
  "tropical fruits": "fruits tropicaux",
  "water fruit": "fruit aquatique",
  "white pear": "poire blanche",
  "wild strawberry": "fraise des Bois",
  "wild strawberry leaf": "feuille de Fraisier sauvage",
  "williams pear": "poire Williams",
  "yellow fruits": "fruits jaunes",
  "yellow plum": "prune jaune",
  "black fig": "figue noire",
  "mulberry": "mûre",
  "prickly pear": "figue de Barbarie",
  "citruses with sugar": "agrumes sucrés",
  "buriti": "buriti",
  "cherimoya": "chérimole",
  "cupuacu, cupuassu, copoasu": "cupuaçu",
  "indian mango": "mangue d'Inde",
  "frozen mango": "mangue givrée",
  "tucumã": "tucumã",
  "pink pepper": "poivre rose",
  "black pepper": "poivre noir",
  "black and pink pepper": "poivre noir et rose",
  "pepper": "poivre",
  "sichuan pepper": "poivre du Sichuan",
  "green pepper": "poivre vert",
  "saffron": "safran",
  "cardamom": "cardamome",
  "cardamon": "cardamome",
  "guatemalan cardamom": "cardamome du Guatemala",
  "cinnamon": "cannelle",
  "clove": "clou de girofle",
  "cloves": "clou de girofle",
  "nutmeg": "noix de muscade",
  "ginger": "gingembre",
  "caraway": "carvi",
  "coriander": "coriandre",
  "cumin": "cumin",
  "anise": "anis",
  "licorice": "réglisse",
  "curry tree": "kaloupilé",
  "basil": "basilic",
  "thyme": "thym",
  "red thyme": "thym rouge",
  "sage": "sauge",
  "clary sage": "sauge sclarée",
  "rosemary": "romarin",
  "tarragon": "estragon",
  "oregano": "origan",
  "exotic spices": "épices exotiques",
  "bay leaf": "feuille de laurier",
  "allspice": "quatre-épices",
  "arabian spices": "épices Arabes",
  "aromatic spices": "épices Aromatiques",
  "asafoetida": "asafoetida",
  "baie rose": "baie rose",
  "basil leaf": "feuille de Basilic",
  "bay essence": "essence de Laurier",
  "bengal pepper": "poivre du Bengale",
  "betel pepper": "bétel",
  "black basil": "basilic noir",
  "black cardamom": "cardamome noire",
  "black licorice": "réglisse noire",
  "bourbon pepper": "poivre Bourbon",
  "caper": "câpre",
  "carrot seeds": "graines de Carotte",
  "celery": "céleri",
  "celery seeds": "graines de Céleri",
  "ceylon cinnamon": "cannelle de Ceylan",
  "chili pepper": "piment",
  "chinese cinnamon wood": "bois de Cannelle de Chine",
  "cilantro": "coriandre",
  "cinammon": "cannelle",
  "cinnamon leaf": "feuille de Cannelier",
  "clove leaf": "feuille de Giroflier",
  "coriander extract": "extrait de Coriandre",
  "coriander leaf": "feuille de Coriandre",
  "curry": "curry",
  "dill": "aneth",
  "fennel": "fenouil",
  "fenugreek": "fenugrec",
  "galanga": "galanga",
  "garden dill": "aneth du Jardin",
  "green bell pepper": "poivron vert",
  "green coriander": "coriandre verte",
  "indian ginger": "gingembre indien",
  "indian saffron": "safran d'Inde",
  "indian spices": "épices indiennes",
  "indian white pepper": "poivre blanc d'Inde",
  "indonesian nutmeg": "noix de Muscade d'Indonésie",
  "indonesian pepper": "poivre d'Indonésie",
  "israeli basil": "basilic d'Israël",
  "madagascar cloves": "clous de Girofle de Madagascar",
  "madagascar pepper": "poivre de Madagascar",
  "mace": "macis",
  "marjoram": "marjolaine",
  "nigerian ginger": "gingembre du Nigeria",
  "nutmeg flower": "fleur de Muscade",
  "orange pepper": "poivre orange",
  "paprika": "paprika",
  "pepper oil": "huile de Poivre",
  "peppermint": "menthe poivrée",
  "peppertree": "poivrier",
  "pepperwood or hercules club": "bois de Poivre ou Clavaire d'Hercule",
  "pepperwood™": "pepperwood™",
  "peruvian pepper": "poivre du Pérou",
  "pimento": "piment",
  "pimento leaf": "feuille de Piment",
  "pimento seeds": "graines de Piment",
  "red chilli pepper": "piment rouge",
  "red pepper": "poivre rouge",
  "satureja": "sarriette",
  "spiked pepper": "poivre long",
  "star anise": "anis étoilé",
  "sweet pepper": "poivron doux",
  "timur": "timut",
  "turmeric": "curcuma",
  "white cardamom": "cardamome blanche",
  "white pepper": "poivre blanc",
  "rose": "rose",
  "bulgarian rose": "rose de Bulgarie",
  "turkish rose": "rose de Turquie",
  "jasmine": "jasmin",
  "lavender": "lavande",
  "iris": "iris",
  "white iris": "iris blanc",
  "violet": "violette",
  "tuberose": "tubéreuse",
  "gardenia": "gardénia",
  "ylang-ylang": "ylang-ylang",
  "neroli": "néroli",
  "orange blossom": "fleur d'oranger",
  "magnolia": "magnolia",
  "peony": "pivoine",
  "muguet": "muguet",
  "lily of the valley": "muguet",
  "lily": "lys",
  "water lily": "nénuphar",
  "freesia": "freesia",
  "hyacinth": "jacinthe",
  "narcissus": "narcisse",
  "orchid": "orchidée",
  "geranium": "géranium",
  "heliotrope": "héliotrope",
  "mimosa": "mimosa",
  "osmanthus": "osmanthus",
  "chamomile": "camomille",
  "honeysuckle": "chèvrefeuille",
  "floral notes": "notes florales",
  "african freesia petals": "pétales de Freesia Africain",
  "african geranium": "géranium Africain",
  "african marigold": "tagète Africain",
  "african orange flower": "fleur d'Oranger Africaine",
  "alba rose": "rose Alba",
  "amaryllis": "amaryllis",
  "amazon lily": "lys d'Amazonie",
  "amethyst flower": "fleur d'Améthyste",
  "ashoka flower": "fleur d'Ashoka",
  "azalea": "azalée",
  "azteca lily": "lys Aztèque",
  "bellflower": "campanule",
  "bitter orange blossom": "fleur d'Oranger amer",
  "black iris": "iris noir",
  "black orchid": "orchidée noire",
  "black rose": "rose noire",
  "black violet": "violette noire",
  "blue hyacinth": "jacinthe bleue",
  "blue lotus": "lotus bleu",
  "blue poppy": "pavot bleu",
  "blue rose": "rose bleue",
  "blue sage": "sauge bleue",
  "bluebell": "jacinthe des Bois",
  "boronia": "boronia",
  "bougainvillea": "bougainvillier",
  "bourbon geranium": "géranium Bourbon",
  "bourbon rose": "rose Bourbon",
  "buddleia": "buddleia",
  "butterfly orchid": "orchidée Papillon",
  "cactus flower": "fleur de Cactus",
  "californian gardenia": "gardénia de Californie",
  "calla lily": "calla",
  "calycanthus": "calycanthus",
  "camelia": "camélia",
  "camellia": "camélia",
  "campion flower": "fleur de Silène",
  "candied flowers": "fleurs confites",
  "carnation": "œillet",
  "casablanca lily": "lys de Casablanca",
  "chinese jasmine": "jasmin de Chine",
  "chinese osmanthus": "osmanthus de Chine",
  "chinese peony": "pivoine de Chine",
  "chinese pink peony": "pivoine Rose de Chine",
  "chocolate flower": "fleur de Chocolat",
  "chrysanthemum": "chrysanthème",
  "corall orchid": "orchidée Corail",
  "cosmos flower": "fleur de Cosmos",
  "cotton flower": "fleur de Coton",
  "creamy flowers": "fleurs crémeuses",
  "cyclamen": "cyclamen",
  "dahlia": "dahlia",
  "daisy": "marguerite",
  "damask rose": "rose de Damas",
  "daphne": "daphné",
  "desert rose": "rose du Désert",
  "dried rose": "rose séchée",
  "egyptian jasmine": "jasmin d'Égypte",
  "egyptian pelargonium": "pélargonium d'Égypte",
  "english rose": "rose anglaise",
  "exotic floral notes": "notes florales exotiques",
  "false jasmine": "faux Jasmin",
  "fire lily": "lis de Feu",
  "flamingo flower": "anthurium",
  "floral fruity notes": "notes Florales fruitées",
  "floral bouquet": "bouquet floral",
  "flower petals": "pétales de Fleurs",
  "flower prism": "prisme floral",
  "flowers": "fleurs",
  "forget me not": "myosotis",
  "frangipani": "frangipanier",
  "freesia petals": "pétales de Freesia",
  "french narcissus": "narcisse de France",
  "french rose": "rose de France",
  "french violet": "violette de France",
  "french orange flower": "fleur d'Oranger de France",
  "fringed pink": "œillet Frangé",
  "fuchsia": "fuchsia",
  "gerbera": "gerbera",
  "ginger flower": "fleur de Gingembre",
  "gladiolus": "glaïeul",
  "golden lily": "lis Doré",
  "grasse rose": "rose de Grasse",
  "green lilac": "lilas vert",
  "green lily": "lis Vert",
  "green lotus": "lotus vert",
  "green orchid": "orchidée verte",
  "gustavia flower": "fleur de Gustavia",
  "hibiscus": "hibiscus",
  "hibiscus blossom": "fleur d'Hibiscus",
  "hibiscus seed": "graine d'Hibiscus",
  "himalayan poppy": "pavot de l'Himalaya",
  "hortensia": "hortensia",
  "impatiens": "impatiente",
  "indian jasmine": "jasmin d'Inde",
  "indian lotus": "lotus d'Inde",
  "indian tuberose": "tubéreuse d'Inde",
  "indonesian carnation": "œillet d'Indonésie",
  "indonesian jasmine": "jasmin d'Indonésie",
  "iris butter": "beurre d'Iris",
  "iris flower": "fleur d'Iris",
  "iris pallida": "iris pallida",
  "iris petals": "pétales d'Iris",
  "iris leaf": "feuille d'Iris",
  "italian iris": "iris d'Italie",
  "italian jasmine": "jasmin d'Italie",
  "italian violet": "violette d'Italie",
  "japanese orchid": "orchidée du Japon",
  "japanese osmanthus": "osmanthe du Japon",
  "japanese pink lotus": "lotus Rose du Japon",
  "jarana flower": "fleur de Jarana",
  "jasmine leaf": "feuille de Jasmin",
  "jasmine orchid": "orchidée Jasmin",
  "jasmine sambac": "jasmin Sambac",
  "jasmine tea": "thé au Jasmin",
  "lady of the night flower": "fleur de Dame de Nuit",
  "lavender extract": "extrait de Lavande",
  "lilac": "lilas",
  "lily-of-the-valley": "muguet",
  "liv tyler rose": "rose Liv Tyler",
  "lotus": "lotus",
  "lotus leaf": "feuille de Lotus",
  "magnolia leaf": "feuille de Magnolia",
  "magnolia petals": "pétales de Magnolia",
  "marigold": "souci",
  "mariposa lily": "lis Mariposa",
  "may rose": "rose de Mai",
  "mayflower": "fleur de Mai",
  "melissa flower": "fleur de Mélisse",
  "michelia": "michelia",
  "mimosa petals": "pétales de Mimosa",
  "mimosa absolute": "absolue de Mimosa",
  "mimosa leaves": "feuilles de Mimosa",
  "moon flower": "fleur de Lune",
  "moroccan jasmine": "jasmin du Maroc",
  "moroccan mimosa": "mimosa du Maroc",
  "moroccan rose": "rose du Maroc",
  "moroccan and indian jasmine": "jasmin du Maroc et d'Inde",
  "moringa blossom": "fleur de Moringa",
  "night blooming jasmine": "jasmin de Nuit",
  "night blooming cereus": "reine de la Nuit",
  "orchard blossom": "fleur de Verger",
  "orchid pink leopard": "orchidée Léopard rose",
  "pansy": "pensée",
  "parma violet": "violette de Parme",
  "passion flower": "fleur de la Passion",
  "pelargonium": "pélargonium",
  "pink crystal": "cristal rose",
  "pink flamingo heliconia": "héliconia Flamant rose",
  "pink freesia": "freesia rose",
  "pink hyacinth": "jacinthe rose",
  "pink jasmine": "jasmin rose",
  "pink lily": "lis Rose",
  "pink lotus": "lotus rose",
  "pink nerium oleander": "laurier-rose",
  "pink peony": "pivoine rose",
  "pink rose": "rose rose",
  "pink violet": "violette rose",
  "pinwheel flower": "fleur Moulinet",
  "plumeria": "frangipanier",
  "poinsettia": "poinsettia",
  "primrose": "primevère",
  "queen of the night flower": "reine de la Nuit",
  "raspberry macaron": "macaron à la Framboise",
  "ravello rose": "rose de Ravello",
  "red cyclamen": "cyclamen rouge",
  "red freesia": "freesia rouge",
  "red lily": "lis Rouge",
  "red peony": "pivoine rouge",
  "red poppy": "coquelicot rouge",
  "red rose": "rose rouge",
  "red tulip": "tulipe rouge",
  "red vanill-orchid": "orchidée Vanille rouge",
  "rose de mai": "rose de Mai",
  "rose geranium": "géranium rosat",
  "rose hip": "cynorrhodon",
  "rose jam": "confiture de Rose",
  "rose leaf": "feuille de Rose",
  "rose mallow": "mauve rose",
  "rose milk": "lait de Rose",
  "rose oil": "huile de Rose",
  "rose oxide": "oxyde de Rose",
  "rose petals": "pétales de Rose",
  "rose thorn": "épine de Rose",
  "rose water": "eau de Rose",
  "rosebay willowherb": "épilobe",
  "rosebud": "bouton de Rose",
  "royal lily": "lis Royal",
  "sand lily": "lis des Sables",
  "sea daffodil": "lis de Mer",
  "silk tree blossom": "fleur d'Arbre à soie",
  "silkwood blossom": "fleur de Bois de soie",
  "skeleton flower": "fleur Squelette",
  "snowdrops": "perce-neige",
  "spanish jasmine": "jasmin d'Espagne",
  "star jasmine": "jasmin étoilé",
  "stephanotis": "stéphanotis",
  "strelitzia": "strelitzia",
  "sweet alyssum": "alysse Odorante",
  "sweet pea": "pois de Senteur",
  "tahitian gardenia": "gardénia de Tahiti",
  "tahitian tiare flower": "fleur de Tiaré de Tahiti",
  "taif rose": "rose de Taïf",
  "tea rose": "rose Thé",
  "tiare": "tiaré",
  "tiare flower": "fleur de Tiaré",
  "tincture of rose": "teinture de Rose",
  "tunisian neroli": "néroli de Tunisie",
  "tunisian orange blossom": "fleur d'Oranger de Tunisie",
  "turkey red rose": "rose Rouge de Turquie",
  "turkish rose oil": "huile de Rose de Turquie",
  "tuscan iris": "iris de Toscane",
  "tyger lily": "lis Tigré",
  "vanilla flower": "fleur de Vanille",
  "vanilla orchid": "orchidée Vanille",
  "violet leaf": "feuille de Violette",
  "violet leaves": "feuilles de Violette",
  "violet root": "racine de Violette",
  "wallflower": "giroflée",
  "water flowers": "fleurs aquatiques",
  "water hyacinth": "jacinthe d'Eau",
  "water jasmine": "jasmin d'Eau",
  "water peony": "pivoine d'Eau",
  "water violet": "violette d'Eau",
  "watery cyclamen": "cyclamen aquatique",
  "white blossom": "fleur blanche",
  "white camelia": "camélia blanc",
  "white cyclamen": "cyclamen blanc",
  "white datura": "datura blanc",
  "white flowers": "fleurs blanches",
  "white ginger lily": "lis Gingembre blanc",
  "white heliotrope": "héliotrope blanc",
  "white hyacinth": "jacinthe blanche",
  "white lily": "lis Blanc",
  "white lotus": "lotus blanc",
  "white magnolia": "magnolia blanc",
  "white mimosa": "mimosa blanc",
  "white mimosa honey": "miel de Mimosa blanc",
  "white nerium oleander": "laurier-rose blanc",
  "white orchid": "orchidée blanche",
  "white rose": "rose blanche",
  "white royal lily": "lis Royal blanc",
  "white violet": "violette blanche",
  "wild jasmine": "jasmin sauvage",
  "wild lavender": "lavande sauvage",
  "wild orchid": "orchidée sauvage",
  "wild peony": "pivoine sauvage",
  "wild rose": "rose sauvage",
  "wildflowers": "fleurs sauvages",
  "wisteria": "glycine",
  "wisteria flower": "fleur de Glycine",
  "yellow champaca": "champaca jaune",
  "yellow freesia": "freesia jaune",
  "yellow narcissus": "narcisse jaune",
  "yellow poppy": "pavot jaune",
  "yellow rose": "rose jaune",
  "yellow water lily": "nénuphar jaune",
  "pink tulip": "tulipe rose",
  "rosa alba": "rosa alba",
  "rosa rubiginosa": "rosa rubiginosa",
  "hamanasu or japanese rose": "hamanasu ou Rose du Japon",
  "transparent flowers": "fleurs transparentes",
  "nerium oleander": "laurier-rose",
  "syringa": "seringa",
  "reseda": "réséda",
  "mignonette": "réséda",
  "larkspur": "dauphinelle",
  "laburnum": "cytise",
  "periwinkle": "pervenche",
  "snowberry": "symphorine",
  "lupin": "lupin",
  "belladonna": "belladone",
  "hellebore flower": "fleur d'Hellébore",
  "datura": "datura",
  "arnica": "arnica",
  "goldenrod": "verge d'Or",
  "borage": "bourrache",
  "heather": "bruyère",
  "protea": "protée",
  "pittosporum": "pittospore",
  "pitosporum": "pittospore",
  "rangoon creeper": "liane de Rangoon",
  "lilybelle®": "lilybelle®",
  "karmaflor®": "karmaflor®",
  "erigeron (fleabane)": "érigéron (Vergerette)",
  "lamprocapnos": "cœur-de-Jeannette",
  "liatris": "liatris",
  "prunella": "brunelle",
  "mirabilis": "mirabilis",
  "santolina": "santoline",
  "lantana": "lantana",
  "lantana leaves": "feuilles de Lantana",
  "jacaranda": "jacaranda",
  "ravenala": "ravenale",
  "phlox": "phlox",
  "azolla": "azolla",
  "dove tree": "arbre aux Mouchoirs",
  "silk vine or milk broom": "vigne de Soie ou Genêt à balais",
  "lydia broom": "genêt de Lydia",
  "broom": "genêt",
  "gorse": "ajonc",
  "dyer's greenweed": "genêt des Teinturiers",
  "cedar": "cèdre",
  "sandalwood": "bois de santal",
  "vetiver": "vétiver",
  "patchouli": "patchouli",
  "oakmoss": "mousse de chêne",
  "guaiac wood": "bois de gaïac",
  "cypress": "cyprès",
  "pine": "pin",
  "fir": "sapin",
  "birch": "bouleau",
  "ebony": "ébène",
  "cashmere wood": "bois de cachemire",
  "amberwood": "bois d'ambre",
  "oud": "oud",
  "agarwood": "bois d'agar",
  "akigalawood": "akigalawood",
  "almond wood": "bois d'Amandier",
  "amyris": "amyris",
  "ash": "frêne",
  "assam oud": "oud d'Assam",
  "atlas cedar": "cèdre de l'Atlas",
  "australian sandalwood": "santal Australien",
  "bamboo": "bambou",
  "bamboo leaf": "feuille de Bambou",
  "bark": "écorce",
  "beech": "hêtre",
  "birch leaf": "feuille de Bouleau",
  "birch tar": "goudron de Bouleau",
  "blackwood": "bois Noir",
  "blonde woods": "bois Blonds",
  "brazilian redwood": "bois Rouge du Brésil",
  "brazilian rosewood": "bois de Rose du Brésil",
  "cabreuva": "cabreuva",
  "california cedar": "cèdre de Californie",
  "california redwood": "séquoia de Californie",
  "cambodian oud": "oud du Cambodge",
  "cashmir wood": "bois de Cachemire",
  "cashmirwood": "cashmirwood",
  "cedar essence": "essence de Cèdre",
  "cedar leaves": "feuilles de Cèdre",
  "cedar needles": "aiguilles de Cèdre",
  "cedar roots": "racines de Cèdre",
  "cedarmoss": "mousse de Cèdre",
  "cedarwood": "bois de Cèdre",
  "charred wood": "bois Carbonisé",
  "chinese cedar": "cèdre de Chine",
  "chinese oud": "oud de Chine",
  "chinese patchouli": "patchouli de Chine",
  "cocobolo": "cocobolo",
  "cypress leaf": "feuille de Cyprès",
  "dark patchouli": "patchouli sombre",
  "dreamwood": "dreamwood",
  "driftwood": "bois Flotté",
  "dry wood": "bois sec",
  "ebony wood": "bois d'Ébène",
  "egyptian rosewood": "bois de Rose d'Égypte",
  "elm": "orme",
  "exotic woods": "bois exotiques",
  "gaiac": "gaïac",
  "gaiac wood": "bois de Gaïac",
  "georgywood": "georgywood",
  "haitian vetiver": "vétiver d'Haïti",
  "healingwood": "healingwood",
  "hemlock": "ciguë",
  "hinoki": "hinoki",
  "hinoki wood": "bois de Hinoki",
  "ho wood": "bois de Hô",
  "himalayan cedar": "cèdre de l'Himalaya",
  "indian oud": "oud d'Inde",
  "indian patchouli": "patchouli d'Inde",
  "indian sandalwood": "santal d'Inde",
  "indonesian oud": "oud d'Indonésie",
  "indonesian patchouli leaf": "feuille de Patchouli d'Indonésie",
  "italian cypress": "cyprès d'Italie",
  "java vetiver oil": "huile de Vétiver de Java",
  "kashmir wood": "bois du Cachemire",
  "laotian oud": "oud du Laos",
  "larch": "mélèze",
  "leatherwood": "bois de Cuir",
  "madagascar vetiver": "vétiver de Madagascar",
  "madagascar ylang-ylang": "ylang-ylang de Madagascar",
  "mahogany": "acajou",
  "malaysian oud": "oud de Malaisie",
  "massoia": "massoïa",
  "massoia wood": "bois de Massoïa",
  "mopane": "mopane",
  "moroccan cedar": "cèdre du Maroc",
  "mysore sandalwood": "santal de Mysore",
  "oak tree": "chêne",
  "orangewood": "bois d'Oranger",
  "palisander rosewood": "bois de Rose palissandre",
  "patchouli (green)": "patchouli (vert)",
  "patchouli leaf": "feuille de Patchouli",
  "pine tree": "pin",
  "pine tree needles": "aiguilles de Pin",
  "pine needles": "aiguilles de Pin",
  "pine tar": "goudron de Pin",
  "precious woods": "bois Précieux",
  "red cedar": "cèdre rouge",
  "red sandalwood": "santal rouge",
  "redwood": "séquoia",
  "redwood flower": "fleur de Séquoia",
  "sandal": "santal",
  "sandalore™": "sandalore™",
  "sandalowood": "bois de Santal",
  "sandalwood flower": "fleur de Santal",
  "satinwood": "satiné",
  "sequoia": "séquoia",
  "serbian oakmoss": "mousse de Chêne serbe",
  "siberian pine": "pin de Sibérie",
  "silver fir": "sapin Argenté",
  "silver pine": "pin Argenté",
  "singapore patchouli": "patchouli de Singapour",
  "spruce": "épicéa",
  "sycamore": "sycomore",
  "tahitian vetiver": "vétiver de Tahiti",
  "tamboti wood": "bois de Tamboti",
  "teak wood": "bois de Teck",
  "texas cedar": "cèdre du Texas",
  "thailand oud": "oud de Thaïlande",
  "thanaka wood": "bois de Thanaka",
  "thuja": "thuya",
  "timberol": "timberol",
  "transparent woods": "bois Transparents",
  "tuscan cypress": "cyprès de Toscane",
  "velvet woods": "bois Veloutés",
  "vetiver root": "racine de Vétiver",
  "vetyver": "vétiver",
  "vietnamese oud": "oud du Vietnam",
  "virginia cedar": "cèdre de Virginie",
  "virginian cedar": "cèdre de Virginie",
  "virginian patchouli": "patchouli de Virginie",
  "white cedar extract": "extrait de Cèdre blanc",
  "white oud": "oud blanc",
  "white sandalwood": "santal blanc",
  "white wood": "bois Blanc",
  "white woods": "bois Blancs",
  "wolfwood": "bois de Loup",
  "wood resin": "résine de Bois",
  "woodsy notes": "notes Boisées",
  "woody notes": "notes Boisées",
  "dark woodsy notes": "notes Boisées sombres",
  "ebony tree": "ébène",
  "boxwood": "buis",
  "black hemlock or tsuga": "pruche du Canada (Tsuga)",
  "black locust": "robinier",
  "poplar": "peuplier",
  "poplar (populus) buds": "bourgeons de Peuplier (Populus)",
  "poplar buds": "bourgeons de Peuplier",
  "black locust  honey": "miel de Robinier",
  "black locust honey": "miel de Robinier",
  "siriuba tree": "bois de Siriuba",
  "amber": "ambre",
  "incense": "encens",
  "frankincense": "oliban",
  "myrrh": "myrrhe",
  "benzoin": "benjoin",
  "labdanum": "labdanum",
  "tolu balsam": "baume de Tolu",
  "balsamic notes": "notes balsamiques",
  "resins": "résines",
  "opoponax": "opoponax",
  "elemi": "élémi",
  "styrax": "styrax",
  "amber xtreme": "ambre Xtreme",
  "amberever": "amberever",
  "ambergris": "ambre Gris",
  "ambermax™": "ambermax™",
  "ambertonic": "ambertonic",
  "ambrarome": "ambrarome",
  "ambreine": "ambréine",
  "ambretone": "ambretone",
  "ambrettolide": "ambrettolide",
  "ambrinol": "ambrinol",
  "ambrocenide": "ambrocenide",
  "ambrofix™": "ambrofix™",
  "ambronova ™": "ambronova ™",
  "ambrostar™": "ambrostar™",
  "ambrox super": "ambrox Super",
  "ambrox® super": "ambrox® Super",
  "black amber": "ambre Noir",
  "breu-branco": "breu-Branco",
  "canada balsam": "baume du Canada",
  "canadian balsam": "baume du Canada",
  "copahu balm": "baume de Copahu",
  "copaiba balm": "baume de Copaïba",
  "copal": "copal",
  "coral amber": "ambre Corail",
  "crystal amber": "ambre Cristal",
  "dragon blood resin": "résine de Sang-dragon",
  "egyptian balsam": "baume d'Égypte",
  "elemi resin": "résine d'Élémi",
  "fir resin": "résine de Sapin",
  "french labdanum": "labdanum de France",
  "gurjan balsam": "baume de Gurjum",
  "gurjun balsam": "baume de Gurjun",
  "indonesian myrrh": "myrrhe d'Indonésie",
  "kyara incense": "encens Kyara",
  "light amber": "ambre clair",
  "liquidambar": "liquidambar",
  "moroccan incense": "encens du Maroc",
  "myrhh": "myrrhe",
  "myrrh oil": "huile de Myrrhe",
  "olibanum": "oliban",
  "olibanum sacra resin green": "oliban Sacra résine verte",
  "peru balsam": "baume du Pérou",
  "red amber": "ambre rouge",
  "red myrrh": "myrrhe rouge",
  "resin": "résine",
  "siam": "siam",
  "siam benzoin": "benjoin de Siam",
  "siam resin": "résine de Siam",
  "spanish labdanum": "labdanum d'Espagne",
  "storax": "storax",
  "white amber": "ambre blanc",
  "musk": "musc",
  "white musk": "musc blanc",
  "ambrette (musk mallow)": "ambrette",
  "ambrette": "ambrette",
  "castoreum": "castoréum",
  "civet": "civette",
  "civetta": "civette",
  "leather": "cuir",
  "suede": "daïm",
  "black leather": "cuir Noir",
  "black musk": "musc Noir",
  "cashmere musk": "musc Cachemire",
  "civettone": "civettone",
  "egyptian musk": "musc d'Égypte",
  "fur": "fourrure",
  "gray musk": "musc gris",
  "island musk": "musc des Îles",
  "muscenone": "muscenone",
  "muscone": "muscone",
  "musk mallow": "mauve Musquée",
  "musk vodka": "vodka Musquée",
  "natural musk": "musc Naturel",
  "russian leather": "cuir de Russie",
  "saffiano leather": "cuir Saffiano",
  "skin musk": "musc de Peau",
  "synthetic civet": "civette Synthétique",
  "white leather": "cuir Blanc",
  "white suede": "daim Blanc",
  "green notes": "notes vertes",
  "water notes": "notes aquatiques",
  "marine notes": "notes marines",
  "sea salt": "sel marin",
  "grass": "herbe coupée",
  "galbanum": "galbanum",
  "artemisia": "armoise",
  "wormwood": "absinthe",
  "ivy": "lierre",
  "moss": "mousse",
  "oak": "chêne",
  "tea": "thé",
  "green tea": "thé vert",
  "mate": "maté",
  "verbena": "verveine",
  "angelica": "angélique",
  "papyrus": "papyrus",
  "algae": "algues",
  "aloe vera": "aloe vera",
  "angelica root": "racine d'Angélique",
  "aquatic notes": "notes Aquatiques",
  "black clover": "trèfle Noir",
  "buchu or agathosma": "buchu (Agathosma)",
  "chlorophyll": "chlorophylle",
  "clover": "trèfle",
  "cypriol": "cypriol",
  "cypriol oil": "huile de Cypriol",
  "cypriol oil or nagarmotha": "huile de Cypriol (Nagarmotha)",
  "fern": "fougère",
  "flax": "lin",
  "galbanum leaf": "feuille de Galbanum",
  "green accord": "accord Vert",
  "green forest": "forêt Verte",
  "green grass": "herbe Verte",
  "green leaves": "feuilles Vertes",
  "green sap": "sève Verte",
  "herbal notes": "notes Herbacées",
  "holly": "houx",
  "hyssop": "hysope",
  "iran galbanum": "galbanum d'Iran",
  "laminaria": "laminaire",
  "laurels": "lauriers",
  "laurissilva forest": "forêt de Laurisylve",
  "lichen": "lichen",
  "mint": "menthe",
  "mint tea": "thé à la Menthe",
  "mistletoe": "gui",
  "mugwort": "armoise",
  "nettle": "ortie",
  "nettle blossom": "fleur d'Ortie",
  "oak leaves": "feuilles de Chêne",
  "pennyroyal": "menthe Pouliot",
  "posidonia": "posidonie",
  "rain notes": "notes de Pluie",
  "red algae": "algue Rouge",
  "reed": "roseau",
  "river notes": "notes de Rivière",
  "roots": "racines",
  "sea buckthorn": "argousier",
  "sea notes": "notes Marines",
  "sea water": "eau de Mer",
  "seagrass": "posidonie",
  "seaweed": "algue",
  "shiso": "shiso",
  "south african sage": "sauge d'Afrique du Sud",
  "spearmint": "menthe Verte",
  "stems greens": "tiges Vertes",
  "sweet grass": "herbe Douce",
  "tea leaf": "feuille de Thé",
  "valerian": "valériane",
  "vegetal notes": "notes Végétales",
  "vervain": "verveine",
  "water mint": "menthe Aquatique",
  "watery notes": "notes Aqueuses",
  "west indian bay": "laurier des Antilles",
  "woodruff or galium odoratum": "aspérule Odorante",
  "vanilla": "vanille",
  "vanila": "vanille",
  "bourbon vanilla": "vanille Bourbon",
  "madagascar vanilla": "vanille de Madagascar",
  "vanilla bean": "gousse de vanille",
  "vanilla sugar": "sucre vanillé",
  "tonka bean": "fève tonka",
  "caramel": "caramel",
  "chocolate": "chocolat",
  "cocoa": "cacao",
  "cacao": "cacao",
  "honey": "miel",
  "white honey": "miel blanc",
  "almond": "amande",
  "bitter almond": "amande amère",
  "sweet almond": "amande douce",
  "almond milk": "lait d'amande",
  "praline": "praliné",
  "coffee": "café",
  "roasted coffee beans": "grains de café torréfiés",
  "chestnut": "marron",
  "hazelnut": "noisette",
  "marshmallow": "guimauve",
  "cotton candy": "barbe à papa",
  "sugar": "sucre",
  "brown sugar": "sucre roux",
  "lactonic": "lacté",
  "milk": "lait",
  "ice cream": "glace",
  "popcorn": "pop-corn",
  "carrot": "carotte",
  "almond blossom": "fleur d'Amandier",
  "almond cream": "crème d'Amande",
  "almond tree": "amandier",
  "amaretto": "amaretto",
  "biscotti": "biscotti",
  "biscuit": "biscuit",
  "bonbon": "bonbon",
  "brioche": "brioche",
  "bubble gum": "bubble gum",
  "bubbaloo": "bubbaloo",
  "burnt sugar": "sucre Brûlé",
  "butter": "beurre",
  "buttermilk": "babeurre",
  "butterscotch": "caramel au Beurre",
  "cacao blossom": "fleur de Cacao",
  "cacao butter": "beurre de Cacao",
  "cacao pod": "cabosse de Cacao",
  "caffè latte": "caffè latte",
  "cake": "gâteau",
  "candied almond": "amande Confite",
  "candied ginger": "gingembre Confit",
  "candied lemon": "citron Confit",
  "candied orange": "orange Confite",
  "candies": "bonbons",
  "candy apple": "pomme d'Amour",
  "canelé": "canelé",
  "cappuccino": "cappuccino",
  "chocolate fudge": "fondant au Chocolat",
  "chocolate truffle": "truffe au Chocolat",
  "cocoa shell": "coque de Cacao",
  "coffee co2": "café CO2",
  "coffee blossom": "fleur de Caféier",
  "columbian coffee": "café Colombien",
  "condensed milk": "lait Concentré",
  "cone waffle": "cornet de Gaufre",
  "confetti (sugared almonds)": "dragées (Amandes Sucrées)",
  "cookie": "cookie",
  "cookie dough": "pâte à Cookie",
  "coton candy": "barbe à Papa",
  "coumarin": "coumarine",
  "cream": "crème",
  "creme brulee": "crème Brûlée",
  "croissant": "croissant",
  "cupcake": "cupcake",
  "custard": "crème Anglaise",
  "dark chocolate": "chocolat Noir",
  "dark chocolate liqueur": "liqueur de Chocolat noir",
  "dragée": "dragée",
  "dulce de leche": "dulce de leche",
  "espresso": "espresso",
  "ethylvanillin": "éthylvanilline",
  "fior di latte": "fior di latte",
  "fresh almond": "amande Fraîche",
  "fresh cream": "crème Fraîche",
  "frosting": "glaçage",
  "frosting [glacé]": "glaçage [Glacé]",
  "frothed milk": "lait Moussé",
  "gelato": "gelato",
  "gingerbread": "pain d'Épices",
  "glacé": "glacé",
  "gummy candies": "bonbons Gélifiés",
  "halva": "halva",
  "hazelnut cocoa spread": "pâte à Tartiner noisette-cacao",
  "honeycomb": "rayon de Miel",
  "icing pink": "rose Bonbon",
  "indian vanilla": "vanille d'Inde",
  "jelly": "gelée",
  "jellybean": "jelly bean",
  "knafeh": "knafeh",
  "kulfi": "kulfi",
  "lactones": "lactones",
  "lemon meringue pie": "tarte au Citron meringuée",
  "macadamia": "macadamia",
  "macadamia flower": "fleur de Macadamia",
  "macarons": "macarons",
  "macchiato": "macchiato",
  "madeleine": "madeleine",
  "malt": "malt",
  "maltol": "maltol",
  "maple": "érable",
  "maple syrup": "sirop d'Érable",
  "marmalade": "marmelade",
  "marron glace": "marron Glacé",
  "marshamallow": "guimauve",
  "marzipan": "pâte d'Amande",
  "masala chai": "chai Masala",
  "mascarpone cheese": "mascarpone",
  "matcha tea": "thé Matcha",
  "meringue": "meringue",
  "mexican vanilla": "vanille du Mexique",
  "mexican chocolate": "chocolat Mexicain",
  "milk candy": "bonbon au Lait",
  "milk chocolate": "chocolat au Lait",
  "milk cream": "crème de Lait",
  "milk mousse": "mousse de Lait",
  "milkshake": "milkshake",
  "mocha": "moka",
  "molasses": "mélasse",
  "natural vanilla": "vanille Naturelle",
  "nougat": "nougat",
  "nutella": "nutella",
  "nutty notes": "notes de Fruits à coque",
  "panacotta": "panna cotta",
  "pancake": "pancake",
  "panettone": "panettone",
  "panna cotta": "panna cotta",
  "peanut": "cacahuète",
  "peanut butter": "beurre de Cacahuète",
  "pecan": "noix de Pécan",
  "pistachio": "pistache",
  "pistachio leaf": "feuille de Pistachier",
  "pistachio liquer": "liqueur de Pistache",
  "pistachio spread cream": "crème de Pistache à tartiner",
  "powdered sugar": "sucre Glace",
  "pretzel": "bretzel",
  "puff pastry": "pâte Feuilletée",
  "roasted nuts": "fruits à Coque grillés",
  "sacher torte": "torte Sacher",
  "salted caramel": "caramel au Beurre salé",
  "salted caramel fudge": "fudge au Caramel salé",
  "sesame": "sésame",
  "black sesame": "sésame Noir",
  "sorbet": "sorbet",
  "speculoos": "speculoos",
  "sprinkles": "vermicelles",
  "spun sugar": "sucre Filé",
  "sugar cane": "canne à Sucre",
  "sugar syrup": "sirop de Sucre",
  "syrup": "sirop",
  "tahitian vanilla": "vanille de Tahiti",
  "tiramisu": "tiramisu",
  "toffee": "caramel Mou",
  "tonka": "fève Tonka",
  "tres leches": "tres leches",
  "truffle": "truffe",
  "vanilla absolute": "absolue de Vanille",
  "vanilla bahiana": "vanille Bahiana",
  "vanilla caviar": "caviar de Vanille",
  "vanilla pod": "gousse de Vanille",
  "vanille": "vanille",
  "vanillin": "vanilline",
  "waffle": "gaufre",
  "walnut": "noix",
  "walnut milk": "lait de Noix",
  "white almond": "amande Blanche",
  "white chocolate": "chocolat Blanc",
  "white chocolate truffle": "truffe au Chocolat blanc",
  "whipped cream": "chantilly",
  "yogurt": "yaourt",
  "brazil nut": "noix du Brésil",
  "cashew": "noix de Cajou",
  "ambroxan": "ambroxan",
  "iso e super": "iso e super",
  "hedione": "hédione",
  "cashmeran": "cashmeran",
  "norlimbanol": "norlimbanol",
  "sylkolide": "sylkolide",
  "mahonial": "mahonial",
  "pomarose": "pomarose",
  "belambra tree": "belambra",
  "calone": "calone",
  "acetylfuran": "acétylfurane",
  "aqual": "aqual",
  "aquozone": "aquozone",
  "amyl salicylate": "salicylate d'Amyle",
  "belanis": "belanis",
  "calypsone": "calypsone",
  "cascalone": "cascalone",
  "cashalox": "cashalox",
  "cetalox": "cetalox",
  "clearwood": "clearwood",
  "cosmofruit™": "cosmofruit™",
  "cosmofruit™ (iff)": "cosmofruit™ (IFF)",
  "cosmone": "cosmone",
  "cocoapulse™": "cocoapulse™",
  "crystalfizz": "crystalfizz",
  "dihydromyrcenol": "dihydromyrcénol",
  "diviniris": "diviniris",
  "dodecanal": "dodécanal",
  "evernyl": "evernyl",
  "factor x": "facteur X",
  "floralozone": "floralozone",
  "floratta dna": "floratta DNA",
  "galaxolide": "galaxolide",
  "geosmin": "géosmine",
  "guaiacol": "gaïacol",
  "habanolide®": "habanolide®",
  "helvetolide": "helvetolide",
  "hexyl acetate": "acétate d'Hexyle",
  "hivernal®": "hivernal®",
  "indole": "indole",
  "jasmolactone": "jasmolactone",
  "javanol": "javanol",
  "kephalis": "kephalis",
  "karo karounde": "karo Karounde",
  "karo-korund": "karo-Korund",
  "lorenox": "lorenox",
  "lysylang": "lysylang",
  "magnolan": "magnolan",
  "maninka": "maninka",
  "methyl pamplemousse": "méthyl Pamplemousse",
  "moxalone": "moxalone",
  "mugane": "mugane",
  "mystikal": "mystikal",
  "naturalcalm™": "naturalcalm™",
  "norlimbanol™": "norlimbanol™",
  "nympheal™": "nympheal™",
  "operanide": "operanide",
  "orcanox™": "orcanox™",
  "osmasylk natsublim™": "osmasylk Natsublim™",
  "pamplewood": "pamplewood",
  "paradisone": "paradisone",
  "pearadise®": "pearadise®",
  "petalia": "petalia",
  "physcool®": "physcool®",
  "prunol": "prunol",
  "rosyfolia": "rosyfolia",
  "safraleine": "safraline",
  "scent trek®": "scent Trek®",
  "sclarene": "sclarène",
  "serenolide": "sérénolide",
  "sinfonide": "sinfonide",
  "sublimolide™": "sublimolide™",
  "suederal®": "suederal®",
  "tonquitone™": "tonquitone™",
  "toscanol": "toscanol",
  "trimofix®": "trimofix®",
  "velvione™": "velvione™",
  "z-11 hd": "z-11 HD",
  "z11™": "z11™",
  "zefir": "zéphyr",
  "sp3 carbon": "carbone SP3",
  "cannabis": "cannabis",
  "rum": "rhum",
  "whiskey": "whisky",
  "gin": "gin",
  "cognac": "cognac",
  "tobacco": "tabac",
  "smoke": "fumée",
  "advocaat": "advocaat",
  "aperol": "aperol",
  "beer/ale": "bière",
  "bellini": "bellini",
  "bourbon whiskey": "whisky Bourbon",
  "brandy": "brandy",
  "bulgarian light tobacco": "tabac Blond bulgare",
  "cachaça": "cachaça",
  "caipirinha": "caïpirinha",
  "campari": "campari",
  "champagne": "champagne",
  "champagne rosé": "champagne Rosé",
  "cigarette": "cigarette",
  "cuban cigar": "cigare Cubain",
  "curacao": "curaçao",
  "daiquiri": "daiquiri",
  "hookah": "narguilé",
  "kir royal": "kir Royal",
  "madeira": "madère",
  "margarita": "margarita",
  "martini": "martini",
  "mojito": "mojito",
  "moscow mule": "moscow Mule",
  "mulled wine": "vin Chaud",
  "opium": "opium",
  "prosecco": "prosecco",
  "punch": "punch",
  "red wine": "vin Rouge",
  "sake": "saké",
  "tequila": "tequila",
  "tobacco blossom": "fleur de Tabac",
  "tobacco leaf": "feuille de Tabac",
  "tonic water": "eau Tonique",
  "vermouth": "vermouth",
  "vodka": "vodka",
  "white rum": "rhum Blanc",
  "white tobacco": "tabac Blanc",
  "white wine": "vin Blanc",
  "wine lees": "lie de Vin",
  "powder": "poudré",
  "aldehydes": "aldéhydes",
  "ozonic": "ozoné",
  "mineral": "minéral",
  "earthy notes": "notes terreuses",
  "spices": "épices",
  "woods": "bois",
  "acacia": "acacia",
  "melon or sweet clover": "mélilot",
  "absinthe": "absinthe",
  "agave": "agave",
  "airy note": "note Aérienne",
  "almdudler": "almdudler",
  "alumroot": "heuchère",
  "amarula": "amarula",
  "animal notes": "notes Animales",
  "antillone™": "antillone™",
  "aromatic notes": "notes Aromatiques",
  "artichoke": "artichaut",
  "arum lily": "arum",
  "asphalt": "asphalte",
  "aspic": "aspic",
  "balsam fir": "sapin Baume",
  "balsamic vinegar": "vinaigre Balsamique",
  "barley": "orge",
  "beeswax": "cire d'Abeille",
  "beetroot": "betterave",
  "blood": "sang",
  "blue crystal": "cristal Bleu",
  "boletus edulis": "boletus edulis",
  "boozy notes": "notes Alcoolisées",
  "bran": "son",
  "bread": "pain",
  "brown scotch tape": "ruban Adhésif brun",
  "buckwheat": "sarrasin",
  "buckwheat tea": "thé de Sarrasin",
  "bulrush": "massette",
  "bushman candle": "bougie Bushman",
  "cactus": "cactus",
  "cactus juice": "jus de Cactus",
  "cade oil": "huile de Cade",
  "calamus": "calamus",
  "calissons d'aix": "calissons d'Aix",
  "candle wax": "cire de Bougie",
  "capitiú": "capitiú",
  "carob tree": "caroubier",
  "caviar": "caviar",
  "cep": "cèpe",
  "cereals": "céréales",
  "cheese": "fromage",
  "cheesecake": "cheesecake",
  "chutney": "chutney",
  "chypre notes": "notes Chypre",
  "cistus incanus": "ciste Incanus",
  "clay": "argile",
  "clean notes": "notes Propres",
  "coal": "charbon",
  "cobblestone": "pavé",
  "coca-cola": "coca-cola",
  "cocaine": "cocaïne",
  "cola": "cola",
  "concrete": "béton",
  "cork": "liège",
  "cornflower or sultan seeds": "bleuet (Graines de Sultan)",
  "costus": "costus",
  "creamy notes": "notes Crémeuses",
  "credit cards": "cartes de Crédit",
  "crithmum": "criste Marine",
  "cyperus esculentus": "cyperus esculentus",
  "dandelion": "pissenlit",
  "darjeeling tea": "thé Darjeeling",
  "davana": "davana",
  "dew drop": "goutte de Rosée",
  "dirt": "terre",
  "dried fallen leaves": "feuilles Mortes séchées",
  "dust": "poussière",
  "earl grey tea": "thé Earl Grey",
  "eucalyptus": "eucalyptus",
  "fabric": "tissu",
  "fire": "feu",
  "fish": "poisson",
  "flint": "silex",
  "fougassette": "fougassette",
  "fougère accord": "accord Fougère",
  "fresh note": "note Fraîche",
  "gasoline": "essence",
  "gentiana": "gentiane",
  "ginger leaf": "feuille de Gingembre",
  "ginseng": "ginseng",
  "goat hair tincture": "teinture de Poil de chèvre",
  "gold": "or",
  "gourmand accord": "accord Gourmand",
  "grains": "grains",
  "graphite": "graphite",
  "guarana": "guarana",
  "hand cream": "crème pour les Mains",
  "hashish": "haschisch",
  "hawthorn": "aubépine",
  "hay": "foin",
  "hazel bloosom": "fleur de Noisetier",
  "head space waterfall": "head Space Cascade",
  "henna": "henné",
  "holy water": "eau Bénite",
  "hops": "houblon",
  "horchata": "horchata",
  "hot iron": "fer Chaud",
  "hyrax": "hyracéum",
  "ice": "glace",
  "iced tea": "thé Glacé",
  "immortelle": "immortelle",
  "industrial glue": "colle Industrielle",
  "ink": "encre",
  "instant film accord": "accord Film instantané",
  "iodine": "iode",
  "ishpink, ocotea quixos": "ishpink, Ocotea quixos",
  "juniper": "genévrier",
  "juniper berries": "baies de Genévrier",
  "kaffir lime": "combava",
  "kumbaru": "kumbaru",
  "kunzea": "kunzea",
  "kyphi": "kyphi",
  "lapsang souchong tea": "thé Lapsang Souchong",
  "lava": "lave",
  "linen": "lin",
  "lip gloss": "gloss à Lèvres",
  "lipstick": "rouge à Lèvres",
  "liquor": "liqueur",
  "litsea cubeba": "litsea cubeba",
  "longoza": "longoza",
  "loukhoum": "loukoum",
  "mahonia": "mahonia",
  "malva": "mauve",
  "manuka": "manuka",
  "meat": "viande",
  "medlar": "nèfle",
  "metallic notes": "notes Métalliques",
  "mineral notes": "notes Minérales",
  "mitti attar": "attar de Mitti",
  "moepel accord": "accord Moepel",
  "money": "argent",
  "monoi oil": "huile de Monoï",
  "mountain air": "air de Montagne",
  "mousse de saxe": "mousse de Saxe",
  "mud": "boue",
  "mushroom": "champignon",
  "myrtle": "myrte",
  "nagarmotha": "nagarmotha",
  "nail polish": "vernis à Ongles",
  "nard": "nard",
  "nard himalayan (jatamansi)": "nard de l'Himalaya (Jatamansi)",
  "nasturtium": "capucine",
  "nectar": "nectar",
  "oat": "avoine",
  "oily notes": "notes Huileuses",
  "olive": "olive",
  "olive blossom": "fleur d'Olivier",
  "olive leaf": "feuille d'Olivier",
  "olive tree": "olivier",
  "olive flower": "fleur d'Olivier",
  "oolong tea": "thé Oolong",
  "oriental woodsy notes": "notes Boisées orientales",
  "oriental notes": "notes Orientales",
  "orris": "iris",
  "orris root": "racine d'Iris",
  "italian orris root": "racine d'Iris d'Italie",
  "oud smoke": "fumée de Oud",
  "ozonic notes": "notes Ozoniques",
  "palm leaf": "feuille de Palmier",
  "palm tree": "palmier",
  "palmarosa": "palmarosa",
  "palo santo": "palo santo",
  "pandanus": "pandanus",
  "paper": "papier",
  "paperbark": "écorce de Melaleuca",
  "para-cresyl phenyl acetate": "phénylacétate de Para-crésyle",
  "paramela": "paramela",
  "parsley": "persil",
  "pataqueira": "pataqueira",
  "pea": "petit Pois",
  "pearls": "perles",
  "peat": "tourbe",
  "pebbles": "galets",
  "petitgrain paraguay": "petitgrain du Paraguay",
  "petrichor": "pétrichor",
  "pink himalayan sea salt": "sel Rose de l'Himalaya",
  "pinot noir grapes": "raisins de Pinot noir",
  "pizza": "pizza",
  "piña colada": "piña Colada",
  "plantain": "plantain",
  "plastic": "plastique",
  "plastic bag": "sac Plastique",
  "poison": "poison",
  "pollen": "pollen",
  "polygonum": "renouée",
  "portulaca or pigweed": "pourpier",
  "potato": "pomme de Terre",
  "powdery notes": "notes Poudrées",
  "priest's clothes": "vêtements de Prêtre",
  "princess tree or paulownia": "arbre Impérial ou Paulownia",
  "priprioca": "priprioca",
  "pumpkin": "citrouille",
  "red maple": "érable Rouge",
  "rhododendron": "rhododendron",
  "rhubarb": "rhubarbe",
  "rhuburb": "rhubarbe",
  "rice": "riz",
  "rice basmati": "riz Basmati",
  "rice flower": "fleur de Riz",
  "rice powder": "poudre de Riz",
  "rock rose": "ciste",
  "rooibos tea": "thé Rooibos",
  "rubber": "caoutchouc",
  "rumex": "rumex",
  "safflower": "carthame",
  "salt": "sel",
  "sand": "sable",
  "sap": "sève",
  "seashells": "coquillages",
  "shamama attar": "attar de Shamama",
  "silk": "soie",
  "silver": "argent",
  "skatole": "skatole",
  "skin": "peau",
  "slate": "ardoise",
  "snow": "neige",
  "soap": "savon",
  "soil tincture": "teinture de Terre",
  "solar notes": "notes Solaires",
  "soybean": "soja",
  "sparkling accord": "accord Pétillant",
  "spicy notes": "notes Épicées",
  "spray paint": "peinture en Spray",
  "stardust": "poussière d'Étoiles",
  "starfish": "étoile de Mer",
  "steam accord": "accord Vapeur",
  "stone": "pierre",
  "straw": "paille",
  "sulphur": "soufre",
  "sumac": "sumac",
  "sunflower": "tournesol",
  "suntan lotion": "lotion Solaire",
  "sweat": "sueur",
  "sweet notes": "notes Sucrées",
  "talc": "talc",
  "tamarind": "tamarin",
  "tar": "goudron",
  "tea tree oil": "huile d'Arbre à thé",
  "thistle": "chardon",
  "tomato": "tomate",
  "tomato flower": "fleur de Tomate",
  "tomato leaf": "feuille de Tomate",
  "tropical notes": "notes Tropicales",
  "varnish accord": "accord Vernis",
  "velvet": "velours",
  "vinyl": "vinyle",
  "vinyl guaiacol": "gaïacol Vinylique",
  "violet woodsorrel": "oxalis des Bois",
  "vine": "vigne",
  "wasabi": "wasabi",
  "water": "eau",
  "wheat": "blé",
  "white powder": "poudre Blanche",
  "wool": "laine",
  "wood barrel": "fût de Bois",
  "cream soda": "soda à la Crème",
  "gunpowder": "poudre à Canon",
  "juniper berry": "baie de Genièvre",
  "latex": "latex",
  "oak moss": "mousse de Chêne",
  "co2 extracts": "extraits CO2",
  "dragibus": "dragibus",
  "popsicle": "glace à l'Eau",
  "black elder": "sureau Noir",
  "candelilla wax": "cire de Candelilla",
  "egg": "œuf",
  "wax": "cire",
  "wood": "bois",
  "root": "racine",
  "leaf": "feuille",
  "flower": "fleur",
  "fruit": "fruit",
  "seed": "graine",
  "nut": "noix",
  "berry": "baie",
  "cotton": "coton",
  "candle": "bougie",
  "acácia": "acacia",
  "african ginger": "gingembre Africain",
  "agarwood (oud)": "bois d'Agar (Oud)",
  "alpinia": "alpinia",
  "angels trumpet": "trompette des Anges",
  "argan": "argan",
  "baobab": "baobab",
  "black tea": "thé Noir",
  "black vanilla husk": "gousse de Vanille noire",
  "blue lavender": "lavande Bleue",
  "bourbon vetiver": "vétiver Bourbon",
  "canadian fir": "sapin du Canada",
  "cananga": "cananga",
  "candied fruits": "fruits Confits",
  "cascarilla": "cascarille",
  "cassia": "casse",
  "cassia bourbon": "casse Bourbon",
  "champaca": "champaca",
  "chantilly cream": "crème Chantilly",
  "chinese black tea": "thé Noir chinois",
  "chinese tea": "thé de Chine",
  "coral reef": "récif Corallien",
  "daim": "daim",
  "dyer’s greenweed": "genêt des Teinturiers",
  "french pastries": "pâtisseries Françaises",
  "fruity notes": "notes Fruitées",
  "fruity and spicy notes": "notes Fruitées et épicées",
  "green almond": "amande Verte",
  "green tea flower": "fleur de Thé vert",
  "grenadine": "grenadine",
  "hiacynth": "jacinthe",
  "italian tangerine": "mandarine d'Italie",
  "mastic or lentisque": "mastic ou Lentisque",
  "miracle berry": "baie Miracle",
  "mock orange": "seringat",
  "neroli essence": "essence de Néroli",
  "poppy": "coquelicot",
  "priest’s clothes": "vêtements de Prêtre",
  "ravensara": "ravensara",
  "red tea": "thé Rouge",
  "strawberry s’mores": "s'mores à la Fraise",
  "tulip": "tulipe",
  "watercress": "cresson",
  "white currant": "groseille Blanche",
  "white ginger": "gingembre Blanc",
  "white grape": "raisin Blanc",
  "white tea": "thé Blanc",
  "white tea blossom": "fleur de Thé blanc",
  "ylang ylang": "ylang-ylang",
};

// ─── ACCORDS (familles olfactives) ──────────────────────────

const ACCORD_DICT: Record<string, string> = {
  "citrus": "agrumes",
  "woody": "boisé",
  "floral": "floral",
  "white floral": "floral blanc",
  "yellow floral": "floral jaune",
  "rose": "rosé",
  "aromatic": "aromatique",
  "fresh spicy": "épicé frais",
  "warm spicy": "épicé chaud",
  "soft spicy": "épicé doux",
  "amber": "ambré",
  "musky": "musqué",
  "powdery": "poudré",
  "sweet": "sucré",
  "fruity": "fruité",
  "green": "vert",
  "fresh": "frais",
  "aquatic": "aquatique",
  "balsamic": "balsamique",
  "smoky": "fumé",
  "earthy": "terreux",
  "leather": "cuir",
  "animalic": "animal",
  "camphor": "camphré",
  "cannabis": "cannabis",
  "gourmand": "gourmand",
  "herbal": "herbacé",
  "iris": "iris",
  "lavender": "lavande",
  "patchouli": "patchouli",
  "violet": "violette",
  "soapy": "savonneux",
  "champagne": "champagne",
  "alcohol": "alcool",
  "aldehydic": "aldéhydé",
  "anis": "anis",
  "asphault": "asphalte",
  "bbq": "barbecue",
  "beeswax": "cire d'Abeille",
  "bitter": "amer",
  "brown scotch tape": "ruban Adhésif brun",
  "clay": "argile",
  "coca-cola": "coca-cola",
  "conifer": "conifère",
  "foresty": "forestier",
  "gasoline": "essence",
  "industrial glue": "colle Industrielle",
  "marine": "marin",
  "meat": "viande",
  "metallic": "métallique",
  "milky": "lacté",
  "mossy": "moussu",
  "nutty": "noisette",
  "oily": "huileux",
  "paper": "papier",
  "plastic": "plastique",
  "rubber": "caoutchouc",
  "sake": "saké",
  "salty": "salé",
  "sand": "sable",
  "savory": "umami",
  "sour": "acide",
  "spice": "épice",
  "tennis ball": "balle de Tennis",
  "terpenic": "terpénique",
  "tropical": "tropical",
  "vinyl": "vinyle",
  "vodka": "vodka",
  "wine": "vin",
};

// ─── Dictionnaire fusionné ──────────────────────────────────

const FULL_DICT: Record<string, string> = { ...ACCORD_DICT, ...NOTE_DICT };

// ─── Fonction publique ──────────────────────────────────────

/** Traduit une note ou un accord EN → FR avec capitalisation.
 *  Fallback : retourne la valeur originale capitalisée. */
export function translateNote(note: string): string {
  if (!note) return note;
  const key = note.toLowerCase().trim();
  const translated = FULL_DICT[key] ?? note;
  // Capitaliser la première lettre
  return translated.charAt(0).toUpperCase() + translated.slice(1);
}
